# Thư mục lưu file ngoài webapp (sửa theo máy chủ triển khai)
ekyc.dir=C:\\Users\\HAI YEN\\Desktop\\Lập trình web BTL\\ekyc
pdf.dir=C:\\Users\\HAI YEN\\Desktop\\Lập trình web BTL\\pdf
pdf_investor.dir=C:\\Users\\HAI YEN\\Desktop\\Lập trình web BTL\\pdf_investor
